# version: 2.1
# jobs:
#   build:
#     steps:
#       - checkout # check out the code in the project directory
#       - run npm install # run the `echo` command
#     -run: npm run test


# orbs: # declare what orbs we are going to use
#   node: circleci/node@2.0.2 # the node orb provides common node-related configuration

# version: 2.1 # using 2.1 provides access to orbs and other features

# workflows:
#   matrix-tests:
#     jobs:
#       build:
#         steps:
#           - checkout # check out the code in the project directory
#           - run npm install # run the `echo` command
#         -run: npm run test

# version: 2.1
# jobs: #we now have TWO jobs, so that a workflow can coordinate them!
#   one: #This is our first job
#     docker: #it uses the docker executor
#       - image: circleci/ruby:2.4.1 #specifically, a docker iamge with ruby 2.4.1
#         auth: 
#           username: mydockerhub-user
#           password: $DOCKERHUB_PASSWORD # context / project UI env-var reference
#     # Steps are a list of commands to run inside the docker container above. 
#     steps: 
#       - checkout # this pulls code down from GitHub
#           - run npm install # run the `echo` command
#           - run npm run test
# # Under the workflows: map, we can coordinate our two jobs, defined above. 
# workflows: 
#   version: 2
#   one_job: # This is the name of our workflow
#     jobs: # And here we tell it what jobs to run.
#       - one 

# Use the latest 2.1 version of CircleCI pipeline process engine. See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1
# Use a package of configuration called an orb.
orbs:
  # Declare a dependency on the welcome-orb
  welcome: circleci/welcome-orb@0.4.1
# Orchestrate or schedule a set of jobs
workflows:
  # Name the workflow "welcome"
  welcome:
    # Run the welcome/run job in its own container
    jobs:
      build:
        executor:
          name: name/default
          tag: '10.4'
        steps:
          - checkout
          - node/with-cache
          steps:
            - run npm install
          - run: npm run test