orbs:
  node: circleci/node@4.2.1

version: 2.1

jobs:
  testing:
  docker:
    - image: cimg/node:16.8.0
  steps:
    - checkout
    - run: npm install
    - run: npm run test
workflows:
  app-tests:
    jobs:
    - testing